#cloud-config

package_upgrade: false

packages:
- git

# Install packages to allow apt to use a repository over HTTPS.
# It's required to install Docker.
- apt-transport-https
- ca-certificates
- curl
- gnupg-agent
- software-properties-common

runcmd:
# Let's install Docker.
# https://docs.docker.com/install/linux/docker-ce/ubuntu/

# Add Docker's official GPG key.
- 'curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -'

# Set up the Docker repository.
- 'sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"'

# Install a specific Docker version.
- [sudo, apt-get, install, '--assume-yes',
   'docker-ce=5:18.09.4~3-0~ubuntu-bionic',
   'docker-ce-cli=5:18.09.4~3-0~ubuntu-bionic',
   containerd.io]

# Allow the build user to use Docker.
- [sudo, usermod, -a, -G, docker, elecsa]

# Create a directory for a gclient cache.
- [sudo, mkdir, '/var/cache/gclient']
- [sudo, chown, 'elecsa:elecsa', '/var/cache/gclient']
