# https://domoreexp.visualstudio.com/Teamspace/_build?definitionId=2879
#
# Build an Electron Release with the "vscode" flavour.

trigger: none

jobs:
- template: templates/build/build_electron_release.yml
  parameters:
    flavour: vscode
