# https://domoreexp.visualstudio.com/Teamspace/_build?definitionId=2708
#
# Lint Electron and Microsoft files.

trigger: none

resources:
  repositories:
  - repository: SkypeSpaces-Infra
    type: git
    name: SkypeSpaces-Infra

jobs:
- template: templates/job/lint.yml
  parameters:
    platform: mac
