# https://domoreexp.visualstudio.com/Teamspace/_build?definitionId=3709

trigger: none

parameters:
- name: buildId
  displayName: Electron build ID
  type: number

resources:
  repositories:
  - repository: SkypeSpaces-Infra
    type: git
    name: SkypeSpaces-Infra

jobs:
- template: templates/multi_job/run_security_tools.yml
  parameters:
    buildId: ${{ parameters.buildId }}
